services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    command:
      - "-N 1000"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/:ro
